-- MySQL Script generated by MySQL Workbench
-- lun. 19 nov. 2018 05:45:47 WAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e_publish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_publish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_publish` DEFAULT CHARACTER SET utf8 ;
USE `e_publish` ;

-- -----------------------------------------------------
-- Table `e_publish`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`sections` (
  `idsections` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NULL,
  `abbr` VARCHAR(45) NULL,
  PRIMARY KEY (`idsections`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`sessions` (
  `idsessions` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NOT NULL,
  `abbr` VARCHAR(45) NULL,
  PRIMARY KEY (`idsessions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`gestion_annees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`gestion_annees` (
  `idgestion_annees` INT NOT NULL AUTO_INCREMENT,
  `annee_debut` YEAR NULL,
  `annee_fin` YEAR NULL,
  `annee_format` VARCHAR(45) NULL,
  PRIMARY KEY (`idgestion_annees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`session_actives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`session_actives` (
  `idsession_active` INT NOT NULL AUTO_INCREMENT,
  `id_sessions` INT NOT NULL,
  `annee` INT NOT NULL,
  `statut` ENUM('0', '1') NULL,
  `date_active` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idsession_active`),
  INDEX `fk_session_actives_sessions1_idx` (`id_sessions` ASC),
  INDEX `fk_session_actives_gestion_annees1_idx` (`annee` ASC),
  CONSTRAINT `fk_session_actives_sessions1`
    FOREIGN KEY (`id_sessions`)
    REFERENCES `e_publish`.`sessions` (`idsessions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_actives_gestion_annees1`
    FOREIGN KEY (`annee`)
    REFERENCES `e_publish`.`gestion_annees` (`idgestion_annees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`facultes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`facultes` (
  `idfacultes` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NULL,
  `abbr` VARCHAR(45) NULL,
  `id_section` INT NULL,
  PRIMARY KEY (`idfacultes`),
  INDEX `fk_facultes_sections1_idx` (`id_section` ASC),
  CONSTRAINT `fk_facultes_sections1`
    FOREIGN KEY (`id_section`)
    REFERENCES `e_publish`.`sections` (`idsections`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`promotions` (
  `idpromotions` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NULL,
  `abbr` VARCHAR(45) NULL,
  PRIMARY KEY (`idpromotions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`auditoires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`auditoires` (
  `idauditoires` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NOT NULL,
  `abbr` VARCHAR(45) NULL,
  `id_facultes` INT NOT NULL,
  `id_promotions` INT NOT NULL,
  PRIMARY KEY (`idauditoires`),
  INDEX `fk_auditoires_facultes_idx` (`id_facultes` ASC),
  INDEX `fk_auditoires_promotions1_idx` (`id_promotions` ASC),
  CONSTRAINT `fk_auditoires_facultes`
    FOREIGN KEY (`id_facultes`)
    REFERENCES `e_publish`.`facultes` (`idfacultes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auditoires_promotions1`
    FOREIGN KEY (`id_promotions`)
    REFERENCES `e_publish`.`promotions` (`idpromotions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`etudiants` (
  `matricule` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `postnom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `id_auditoires` INT NOT NULL,
  `annee_acad` INT NOT NULL,
  `statut` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`matricule`),
  INDEX `fk_etudiants_auditoires1_idx` (`id_auditoires` ASC),
  INDEX `fk_etudiants_gestion_annees1_idx` (`annee_acad` ASC),
  CONSTRAINT `fk_etudiants_auditoires1`
    FOREIGN KEY (`id_auditoires`)
    REFERENCES `e_publish`.`auditoires` (`idauditoires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etudiants_gestion_annees1`
    FOREIGN KEY (`annee_acad`)
    REFERENCES `e_publish`.`gestion_annees` (`idgestion_annees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`codes` (
  `idcodes` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `matricule_etudiant` INT NOT NULL,
  `id_sessions` INT NOT NULL,
  `active` ENUM('0', '1') NULL,
  `statut` ENUM('0', '1') NULL,
  PRIMARY KEY (`idcodes`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `fk_codes_session_actives1_idx` (`id_sessions` ASC),
  INDEX `fk_codes_etudiants1_idx` (`matricule_etudiant` ASC),
  CONSTRAINT `fk_codes_session_actives1`
    FOREIGN KEY (`id_sessions`)
    REFERENCES `e_publish`.`session_actives` (`idsession_active`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codes_etudiants1`
    FOREIGN KEY (`matricule_etudiant`)
    REFERENCES `e_publish`.`etudiants` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`bulletins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`bulletins` (
  `idbulletins` INT NOT NULL AUTO_INCREMENT,
  `file` TEXT NULL,
  `matricule_etudiants` INT NOT NULL,
  `id_code` INT NOT NULL,
  `id_session_active` INT NOT NULL,
  PRIMARY KEY (`idbulletins`),
  INDEX `fk_bulletins_codes1_idx` (`id_code` ASC),
  INDEX `fk_bulletins_etudiants1_idx` (`matricule_etudiants` ASC),
  CONSTRAINT `fk_bulletins_codes1`
    FOREIGN KEY (`id_code`)
    REFERENCES `e_publish`.`codes` (`idcodes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bulletins_etudiants1`
    FOREIGN KEY (`matricule_etudiants`)
    REFERENCES `e_publish`.`etudiants` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`users_roles` (
  `idusers_roles` INT NOT NULL AUTO_INCREMENT,
  `lib` VARCHAR(45) NULL,
  `slug` VARCHAR(45) NULL,
  `level` INT NULL,
  PRIMARY KEY (`idusers_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_section` INT NOT NULL,
  `id_role` INT NOT NULL,
  `statut` ENUM('0', '1') NULL,
  `created` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idusers`),
  INDEX `fk_users_users_roles1_idx` (`id_role` ASC),
  INDEX `fk_users_sections1_idx` (`id_section` ASC),
  CONSTRAINT `fk_users_users_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `e_publish`.`users_roles` (`idusers_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_sections1`
    FOREIGN KEY (`id_section`)
    REFERENCES `e_publish`.`sections` (`idsections`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_publish`.`ventes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_publish`.`ventes` (
  `idventes` INT NOT NULL AUTO_INCREMENT,
  `id_users` INT NOT NULL,
  `id_code` INT NOT NULL,
  `date_vente` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idventes`),
  INDEX `fk_ventes_codes1_idx` (`id_code` ASC),
  INDEX `fk_ventes_users1_idx` (`id_users` ASC),
  CONSTRAINT `fk_ventes_codes1`
    FOREIGN KEY (`id_code`)
    REFERENCES `e_publish`.`codes` (`idcodes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventes_users1`
    FOREIGN KEY (`id_users`)
    REFERENCES `e_publish`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
